/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.Controllers.DB.CMSDBKud;
import ehu.isad.Controllers.UI.CMSKud;
import ehu.isad.Controllers.UI.ServerKud;
import ehu.isad.Controllers.UI.WebKud;
import ehu.isad.Controllers.UI.WhatWebKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Callback;

import java.io.IOException;

import static javafx.application.Application.launch;

public class WhatWeb extends Application {

    private Stage stage;
    private Parent nagusiaUI;
    private WhatWebKud whatWebKud;
    private CMSKud cmsKud;
    private ServerKud serverKud;
    private WebKud webKud;

    public CMSKud getCmsKud() {
        return cmsKud;
    }

    public ServerKud getServerKud() {
        return serverKud;
    }

    public WhatWebKud getWhatWebKud() {
        return whatWebKud;
    }

    public void start(Stage primaryStage) throws Exception {

        stage = primaryStage;
        primaryStage.initStyle(StageStyle.UNDECORATED);
        pantailakKargatu();
        stage.setScene(new Scene(nagusiaUI));
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderNagusia = new FXMLLoader(getClass().getResource("/WhatWeb.fxml"));
        whatWebKud = new WhatWebKud();
        serverKud = new ServerKud();
        webKud = new WebKud();
        cmsKud = new CMSKud();


        Callback<Class<?>, Object> controllerFactory = type -> {
            if (type == WhatWebKud.class) {
                return whatWebKud ;
            } else if (type == CMSKud.class) {
                return cmsKud ;
            } else if (type == WebKud.class) {
                return webKud;
            } else if (type == ServerKud.class){
                return serverKud;
            }
                // default behavior for controllerFactory:
                try {
                    return type.newInstance();
                } catch (Exception exc) {
                    exc.printStackTrace();
                    throw new RuntimeException(exc); // fatal, just bail...
                }
            };


        loaderNagusia.setControllerFactory(controllerFactory);

        nagusiaUI = (Parent) loaderNagusia.load();
        whatWebKud = loaderNagusia.getController();
        whatWebKud.setMainApp(this);
        cmsKud.setMain(this);

    }

    public static void main(String[] args) {
        launch(args);
    }
}