/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.Controllers.UI.WhatWebKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

import java.io.IOException;

import static javafx.application.Application.launch;

public class WhatWeb extends Application {

    private Stage stage;
    private Parent nagusiaUI;
    private WhatWebKud whatWebKud;


    public void start(Stage primaryStage) throws Exception {

        stage = primaryStage;
        primaryStage.initStyle(StageStyle.UNDECORATED);
        pantailakKargatu();
        stage.setScene(new Scene(nagusiaUI));
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderNagusia = new FXMLLoader(getClass().getResource("/WhatWeb.fxml"));
        nagusiaUI = (Parent) loaderNagusia.load();
        whatWebKud = loaderNagusia.getController();
        whatWebKud.setMainApp(this);
    }

    public static void main(String[] args) {
        launch(args);
    }
}